/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package drug;

import javax.*;
import static drug.storeinfo.isd;
import java.awt.event.ActionListener;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author ASHWINI A M
 */

public class login extends javax.swing.JFrame {

    private Timer t;
private ActionListener al;

    /**
     * Creates new form login
     */
    public login() {
        
        this.setResizable(false);
        initComponents();
        jPanel4.setEnabled(false);
        jPanel5.setEnabled(false);
        jPanel7.setEnabled(false);
        jLabel1.setEnabled(false);
        jLabel2.setEnabled(false);
        ssubmit.setEnabled(false);
        spass.setEnabled(false);
        sclear.setEnabled(false);
        jLabel3.setEnabled(false);
        apass.setEnabled(false);
        asubmit.setEnabled(false);
        aclear.setEnabled(false);
        jLabel4.setEnabled(false);
        dmit.setEnabled(false);
        dpass.setEnabled(false);
        dclear.setEnabled(false);
        store_id.setEnabled(false);
        did.setEnabled(false);
        jLabel5.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        store_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        spass = new javax.swing.JPasswordField();
        ssubmit = new javax.swing.JButton();
        sclear = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        apass = new javax.swing.JPasswordField();
        asubmit = new javax.swing.JButton();
        aclear = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        dpass = new javax.swing.JPasswordField();
        dmit = new javax.swing.JButton();
        dclear = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        did = new javax.swing.JTextField();

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Administrator Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Retailer login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Store_id:");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });

        store_id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                store_idMouseEntered(evt);
            }
        });
        store_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                store_idActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Password:");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });

        spass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                spassMouseEntered(evt);
            }
        });
        spass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spassActionPerformed(evt);
            }
        });

        ssubmit.setText("Submit");
        ssubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ssubmitMouseEntered(evt);
            }
        });
        ssubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssubmitActionPerformed(evt);
            }
        });

        sclear.setText("Clear");
        sclear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sclearMouseEntered(evt);
            }
        });
        sclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sclearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(store_id)
                    .addComponent(spass)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sclear)
                            .addComponent(ssubmit))
                        .addGap(0, 89, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(store_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(ssubmit)
                .addGap(18, 18, 18)
                .addComponent(sclear)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Administrator Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(0, 0, 255));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Password:");

        apass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                apassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                apassMouseExited(evt);
            }
        });

        asubmit.setText("Submit");
        asubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                asubmitMouseEntered(evt);
            }
        });
        asubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asubmitActionPerformed(evt);
            }
        });

        aclear.setText("Clear");
        aclear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aclearMouseEntered(evt);
            }
        });
        aclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aclearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aclear)
                    .addComponent(asubmit)
                    .addComponent(apass, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(asubmit)
                .addGap(18, 18, 18)
                .addComponent(aclear)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dealer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel7.setForeground(new java.awt.Color(0, 0, 255));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel7MouseExited(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Password:");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
        });

        dpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dpassMouseEntered(evt);
            }
        });

        dmit.setText("Submit");
        dmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dmitMouseEntered(evt);
            }
        });
        dmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dmitActionPerformed(evt);
            }
        });

        dclear.setText("Clear");
        dclear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dclearMouseEntered(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Dealer_id:");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
        });

        did.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                didMouseEntered(evt);
            }
        });
        did.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                didActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(did))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dmit)
                            .addComponent(dclear))
                        .addGap(0, 87, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dpass)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(did, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(dpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(dmit)
                .addGap(18, 18, 18)
                .addComponent(dclear)
                .addGap(26, 26, 26))
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void store_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_store_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_store_idActionPerformed

    private void spassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spassActionPerformed

    private void aclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aclearActionPerformed
apass.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_aclearActionPerformed

    private void asubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asubmitActionPerformed

        try {
            String p=apass.getText();
            if(p.equals("root"))
            {
                JOptionPane.showMessageDialog(jPanel5, "Login Successful", "Administrator login", JOptionPane.INFORMATION_MESSAGE);
                
                
                
                this.dispose();
                
                admin ob=new admin();
                ob.setVisible(true);
            }
            else
                JOptionPane.showMessageDialog(jPanel5, "Login failed", "Unauthorized Access", JOptionPane.INFORMATION_MESSAGE);
            
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","abhij","naanu");
       
            
            
// TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_asubmitActionPerformed

    private void ssubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssubmitActionPerformed

        int i=1;
        
        int u1,f=0,q=0;
        String pass=spass.getText();
        String p1;
        try{
        
        DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
        Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","abhij","naanu");  
        Statement stmt=con.createStatement();
        int u=Integer.parseInt(store_id.getText());
       ResultSet rs=stmt.executeQuery("select * from stores");
       
        while(rs.next()==true)
        {  
            q=1;
            u1=rs.getInt(1);
            p1=rs.getString(6);
            if(u==u1 && pass.equals(p1))
            {
                f=1;
                break;
            }
   
        }
        if(q==1)
        {
        if(f==1)
            {
                JOptionPane.showMessageDialog(jPanel5, "Login Successful", "Retailer login", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                shop obj=new shop(u);
                obj.setVisible(true);
            }

            
            else
            {
                JOptionPane.showMessageDialog(jPanel5, "Invalid Username or Password", "Unauthorized Access", JOptionPane.INFORMATION_MESSAGE);
                
            }
        }
        else
            JOptionPane.showMessageDialog(jPanel5, "No stores are available", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(jPanel5, e, "Invalid Input", JOptionPane.ERROR_MESSAGE);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_ssubmitActionPerformed

    private void dmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dmitActionPerformed

       int i=1;
        
        int u1,f=0,q=0;
        String pass=dpass.getText();
        String p1;
        try{
        
        DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
        Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","abhij","naanu");  
        Statement stmt=con.createStatement();
       ResultSet rs=stmt.executeQuery("select * from dealer");
       int u=Integer.parseInt(did.getText());
        while(rs.next()==true)
        {  
            q=1;
            u1=rs.getInt(1);
            p1=rs.getString(5);
            if(u==u1 && pass.equals(p1))
            {
                f=1;
                break;
            }
   
        }
        if(q==1)
        {
        if(f==1)
            {
                
                
                JOptionPane.showMessageDialog(jPanel2, "Login Successful", "Dealer login", JOptionPane.INFORMATION_MESSAGE);
                
                
                this.dispose();
                dealer2 obj=new dealer2(u);
                obj.setVisible(true);
            }

            
            else
            {
                JOptionPane.showMessageDialog(jPanel2, "Invalid Username or Password", "Unauthorized Access", JOptionPane.INFORMATION_MESSAGE);
                
            }
        }
        else
            JOptionPane.showMessageDialog(jPanel7, "No dealers are available", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(jPanel5, e, "Invalid Input", JOptionPane.ERROR_MESSAGE);
        }

        


        // TODO add your handling code here:
    }//GEN-LAST:event_dmitActionPerformed

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered


        jPanel5.setEnabled(true);
         jLabel3.setEnabled(true);
        apass.setEnabled(true);
        asubmit.setEnabled(true);
        aclear.setEnabled(true);
        


        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
 
        jPanel5.setEnabled(false);
         jLabel3.setEnabled(false);
        apass.setEnabled(false);
        asubmit.setEnabled(false);
        aclear.setEnabled(false);
        
// TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseExited

    private void apassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apassMouseEntered

        jPanel5.setEnabled(true);
         jLabel3.setEnabled(true);
        apass.setEnabled(true);
        asubmit.setEnabled(true);
        aclear.setEnabled(true);

        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_apassMouseEntered

    private void apassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apassMouseExited
   
        
         
        
    }//GEN-LAST:event_apassMouseExited

    private void asubmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asubmitMouseEntered

         jPanel5.setEnabled(true);
         jLabel3.setEnabled(true);
        apass.setEnabled(true);

        asubmit.setEnabled(true);
        aclear.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_asubmitMouseEntered

    private void aclearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aclearMouseEntered

         jPanel5.setEnabled(true);
         jLabel3.setEnabled(true);
        apass.setEnabled(true);
        asubmit.setEnabled(true);
        aclear.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_aclearMouseEntered

    private void didActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_didActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_didActionPerformed

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered

        
        jPanel4.setEnabled(true);
        jLabel1.setEnabled(true);
        jLabel2.setEnabled(true);
        store_id.setEnabled(true);
        spass.setEnabled(true);
        ssubmit.setEnabled(true);
        sclear.setEnabled(true);
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited

        jPanel4.setEnabled(false);
        jLabel1.setEnabled(false);
        jLabel2.setEnabled(false);
        store_id.setEnabled(false);
        spass.setEnabled(false);
        ssubmit.setEnabled(false);
        sclear.setEnabled(false);
        
   
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseExited

    private void store_idMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_store_idMouseEntered

jPanel4.setEnabled(true);
        jLabel1.setEnabled(true);
        jLabel2.setEnabled(true);
        store_id.setEnabled(true);
        spass.setEnabled(true);
        ssubmit.setEnabled(true);
        sclear.setEnabled(true);
    }//GEN-LAST:event_store_idMouseEntered

    private void spassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spassMouseEntered

     jPanel4.setEnabled(true);
        jLabel1.setEnabled(true);
        jLabel2.setEnabled(true);
        store_id.setEnabled(true);
        spass.setEnabled(true);
        ssubmit.setEnabled(true);
        sclear.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_spassMouseEntered

    private void ssubmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ssubmitMouseEntered

jPanel4.setEnabled(true);
        jLabel1.setEnabled(true);
        jLabel2.setEnabled(true);
        store_id.setEnabled(true);
        spass.setEnabled(true);
        ssubmit.setEnabled(true);
        sclear.setEnabled(true);  // TODO add your handling code here:
    }//GEN-LAST:event_ssubmitMouseEntered

    private void sclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sclearActionPerformed

store_id.setText("");
spass.setText("");

    }//GEN-LAST:event_sclearActionPerformed

    private void sclearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sclearMouseEntered
jPanel4.setEnabled(true);
        jLabel1.setEnabled(true);
        jLabel2.setEnabled(true);
        store_id.setEnabled(true);
        spass.setEnabled(true);
        ssubmit.setEnabled(true);
        sclear.setEnabled(true);       // TODO add your handling code here:
    }//GEN-LAST:event_sclearMouseEntered

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
jPanel4.setEnabled(true);
        jLabel1.setEnabled(true);
        jLabel2.setEnabled(true);
        store_id.setEnabled(true);
        spass.setEnabled(true);
        ssubmit.setEnabled(true);
        sclear.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
jPanel4.setEnabled(true);
        jLabel1.setEnabled(true);
        jLabel2.setEnabled(true);
        store_id.setEnabled(true);
        spass.setEnabled(true);
        ssubmit.setEnabled(true);
        sclear.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jPanel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseEntered

        jPanel7.setEnabled(true);
        did.setEnabled(true);
        dpass.setEnabled(true);
        dmit.setEnabled(true);
        dclear.setEnabled(true);
        jLabel5.setEnabled(true);
        jLabel4.setEnabled(true);
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MouseEntered

    private void jPanel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseExited
 
        jPanel7.setEnabled(false);
        did.setEnabled(false);
        dpass.setEnabled(false);
        dmit.setEnabled(false);
        dclear.setEnabled(false);
        jLabel5.setEnabled(false);
        jLabel4.setEnabled(false);// TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MouseExited

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered

jPanel7.setEnabled(true);
        did.setEnabled(true);
        dpass.setEnabled(true);
        dmit.setEnabled(true);
        dclear.setEnabled(true);
        jLabel5.setEnabled(true);
        jLabel4.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseEntered

    private void didMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_didMouseEntered
jPanel7.setEnabled(true);
        did.setEnabled(true);
        dpass.setEnabled(true);
        dmit.setEnabled(true);
        dclear.setEnabled(true);
        jLabel5.setEnabled(true);
        jLabel4.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_didMouseEntered

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered

jPanel7.setEnabled(true);
        did.setEnabled(true);
        dpass.setEnabled(true);
        dmit.setEnabled(true);
        dclear.setEnabled(true);
        jLabel5.setEnabled(true);
        jLabel4.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseEntered

    private void dpassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dpassMouseEntered
jPanel7.setEnabled(true);
        did.setEnabled(true);
        dpass.setEnabled(true);
        dmit.setEnabled(true);
        dclear.setEnabled(true);
        jLabel5.setEnabled(true);
        jLabel4.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_dpassMouseEntered

    private void dclearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dclearMouseEntered
jPanel7.setEnabled(true);
        did.setEnabled(true);
        dpass.setEnabled(true);
        dmit.setEnabled(true);
        dclear.setEnabled(true);
        jLabel5.setEnabled(true);
        jLabel4.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_dclearMouseEntered

    private void dmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dmitMouseEntered
     
        jPanel7.setEnabled(true);
        did.setEnabled(true);
        dpass.setEnabled(true);
        dmit.setEnabled(true);
        dclear.setEnabled(true);
        jLabel5.setEnabled(true);
        jLabel4.setEnabled(true); // TODO add your handling code here:
    }//GEN-LAST:event_dmitMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aclear;
    private javax.swing.JPasswordField apass;
    private javax.swing.JButton asubmit;
    private javax.swing.JButton dclear;
    private javax.swing.JTextField did;
    private javax.swing.JButton dmit;
    private javax.swing.JPasswordField dpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton sclear;
    private javax.swing.JPasswordField spass;
    private javax.swing.JButton ssubmit;
    private javax.swing.JTextField store_id;
    // End of variables declaration//GEN-END:variables
}
