/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package drug;

import java.sql.Connection;
import java.util.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASHWINI A M
 */
public class medicines extends javax.swing.JFrame {

    /**
     * Creates new form medicines
     */
    DefaultTableModel mod;
    public medicines() {
        initComponents();
        rm.setEnabled(false);
        qu.setEnabled(false);
        ud.setVisible(false);
        DefaultTableModel mod;
        
        mod=(DefaultTableModel)jTable1.getModel();
        try{
         DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
        Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","abhij","naanu");  
        Statement stmt=con.createStatement();

    
    ResultSet rs=stmt.executeQuery("select * from medicine");
    String a[]=new String[7];
    String b;
    int i=0;
    
   
    while(rs.next()==true)
    {
         mod.insertRow(mod.getRowCount(),new Object[]{Integer.toString(rs.getInt(1)),(rs.getString(2)),(rs.getString(3)),(rs.getString(4)),(rs.getString(5)),(Integer.toString(rs.getInt(6)))});
    }
    
    con.close();
    }
    catch(Exception e)
    {
        
        JOptionPane.showMessageDialog(jPanel1, e, "Error", JOptionPane.ERROR_MESSAGE);
    }
    }
    public String getd(String a)
    {
        String y=a.substring(0,4);
        String d=a.substring(8,10);
        String m=a.substring(5,7);
        if(m.equals("01"))
           m="jan";
        else if(m.equals("02"))
            m="feb";
        else if(m.equals("03"))
            m="mar";
        else if(m.equals("04"))
            m="apr";
        else if(m.equals("05"))
            m="may";
        else if(m.equals("06"))
            m="jun";
        else if(m.equals("07"))
            m="jul";
        else if(m.equals("08"))
            m="aug";
        else if(m.equals("09"))
            m="sep";
        else if(m.equals("10"))
            m="oct";
        else if(m.equals("11"))
            m="nov";
        else if(m.equals("12"))
            m="dec";
        a=d+"-"+m+"-"+y;
            
        
        
        
        return a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        qu = new javax.swing.JButton();
        rm = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ud = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tt2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tt1 = new javax.swing.JTextField();
        g2 = new javax.swing.JButton();
        g1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Med_id", "Name", "Composition", "DateManf.", "DateExp.", "CostPerUnit"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 690, 340));

        jButton1.setText("Add New..");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        qu.setText("Update");
        qu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quActionPerformed(evt);
            }
        });
        jPanel1.add(qu, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        rm.setText("Remove Medicine");
        rm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmActionPerformed(evt);
            }
        });
        jPanel1.add(rm, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Manage Your Drugs");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 252, -1));

        ud.setText("Update in detail");
        jPanel1.add(ud, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 97, 1402, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drug/herbal_nutritional_supplement_isolated_on_a_white_background.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 800, 480));

        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Search by Composition:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));
        jPanel1.add(tt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 250, 30));

        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Search by name:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));
        jPanel1.add(tt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 250, 30));

        g2.setText("GO");
        g2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g2ActionPerformed(evt);
            }
        });
        jPanel1.add(g2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, -1));

        g1.setText("GO");
        g1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g1ActionPerformed(evt);
            }
        });
        jPanel1.add(g1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, -1));

        jMenu1.setText("File");

        jMenuItem1.setText("Back");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        medinfo obj=new medinfo();
        this.dispose();
        obj.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmActionPerformed

        mod=(DefaultTableModel)jTable1.getModel();
        String val;
        val=String.valueOf((mod.getValueAt(jTable1.getSelectedRow(),0)));
        System.out.println(val);
        int at=Integer.parseInt(val);
        System.out.println(at);
        try{
         DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
        Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","abhij","naanu");  
        Statement stmt=con.createStatement();
    PreparedStatement pstmt = con.prepareStatement("delete from medicine where med_id=?");
    pstmt.setInt(1, at);
    pstmt.executeUpdate();
    mod.removeRow(jTable1.getSelectedRow());  
    con.close();
    }
    catch(Exception e)
    {
        
        JOptionPane.showMessageDialog(jPanel1, e, "Error", JOptionPane.ERROR_MESSAGE);
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_rmActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        ud.setEnabled(true);
        qu.setEnabled(true);
        rm.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void quActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quActionPerformed

                       
            
            mod=(DefaultTableModel)jTable1.getModel();
            String val=String.valueOf((mod.getValueAt(jTable1.getSelectedRow(),0)));
            String val1=String.valueOf((mod.getValueAt(jTable1.getSelectedRow(),1)));
            String val2=String.valueOf((mod.getValueAt(jTable1.getSelectedRow(),2)));
            String val3=String.valueOf((mod.getValueAt(jTable1.getSelectedRow(),3)));
            String val4=String.valueOf((mod.getValueAt(jTable1.getSelectedRow(),4)));
            String val5=String.valueOf((mod.getValueAt(jTable1.getSelectedRow(),5)));
            int v=Integer.parseInt(val);
            int v5=Integer.parseInt(val5);
            val3=val3.substring(0,10);
            val3=getd(val3);
            val4=val4.substring(0,10);
            val4=getd(val4);
            medinfo obj1=new medinfo(v,val1,val2,val3,val4,v5);
            this.dispose();
            obj1.setVisible(true);
            
 

        // TODO add your handling code here:
    }//GEN-LAST:event_quActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        this.dispose();   
        admin obj=new admin();
obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void g1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g1ActionPerformed

try {
            String a=tt1.getText();
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","abhij","naanu");
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery("select * from medicine where name like '%"+a+"%'");
            mod=(DefaultTableModel)jTable1.getModel();
            mod.getDataVector().removeAllElements();
            revalidate();
            while(rs.next()==true)
    {
         mod.insertRow(mod.getRowCount(),new Object[]{Integer.toString(rs.getInt(1)),(rs.getString(2)),(rs.getString(3)),(rs.getString(4)),(rs.getString(5)),(Integer.toString(rs.getInt(6)))});
    }
            tt1.setText("");
            
            
        } catch (SQLException ex) {
            Logger.getLogger(stores.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_g1ActionPerformed

    private void g2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g2ActionPerformed
  
        try {
            String a=tt2.getText();
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","abhij","naanu");
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery("select * from medicine where composition like '%"+a+"%'");
            mod=(DefaultTableModel)jTable1.getModel();
            mod.getDataVector().removeAllElements();
            revalidate();
            while(rs.next()==true)
    {
         mod.insertRow(mod.getRowCount(),new Object[]{Integer.toString(rs.getInt(1)),(rs.getString(2)),(rs.getString(3)),(rs.getString(4)),(rs.getString(5)),(Integer.toString(rs.getInt(6)))});
    }
            tt2.setText("");
            
            
        } catch (SQLException ex) {
            Logger.getLogger(stores.class.getName()).log(Level.SEVERE, null, ex);
        }// TODO add your handling code here:
    }//GEN-LAST:event_g2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(medicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(medicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(medicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(medicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new medicines().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton g1;
    private javax.swing.JButton g2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton qu;
    private javax.swing.JButton rm;
    private javax.swing.JTextField tt1;
    private javax.swing.JTextField tt2;
    private javax.swing.JButton ud;
    // End of variables declaration//GEN-END:variables
}
