/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package drug;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASHWINI A M
 */
public class stores extends javax.swing.JFrame {

    /**
     * Creates new form stores
     */
    DefaultTableModel mod;
    public stores() {
        
        initComponents();
        DefaultTableModel mod;
        nrd.setVisible(false);
        upd.setEnabled(false);
        udd.setEnabled(false);
        del.setEnabled(false);
        mod=(DefaultTableModel)jTable1.getModel();
        try{
         DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
        Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","abhij","naanu");  
        Statement stmt=con.createStatement();

    
    ResultSet rs=stmt.executeQuery("select * from stores");

    String a[]=new String[7];
    String b;
    int i=0;
    
    if(rs.next()==false)
        nrd.setVisible(true);
    else
    {
         mod.insertRow(mod.getRowCount(),new Object[]{Integer.toString(rs.getInt(1)),(rs.getString(2)),(rs.getString(3)),(rs.getString(4)),(rs.getString(5))});
    }
    while(rs.next()==true)
    {
         mod.insertRow(mod.getRowCount(),new Object[]{Integer.toString(rs.getInt(1)),(rs.getString(2)),(rs.getString(3)),(rs.getString(4)),(rs.getString(5))});
    }
    
    con.close();
    }
    catch(Exception e)
    {
        
        JOptionPane.showMessageDialog(jPanel1, e, "Error", JOptionPane.ERROR_MESSAGE);
    }
        
      
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        upd = new javax.swing.JButton();
        del = new javax.swing.JButton();
        nrd = new javax.swing.JLabel();
        udd = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        tt2 = new javax.swing.JTextField();
        g2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tt1 = new javax.swing.JTextField();
        g1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Store_id", "Name", "Store_address", "contact", "Store_Manager"
            }
        ));
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTable1FocusLost(evt);
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTable1InputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 320, 710, 350);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Manage Your Stores");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 20, 290, 47);

        jButton1.setText("Add new..");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(40, 120, 83, 23);

        upd.setText("Quick update");
        upd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updActionPerformed(evt);
            }
        });
        jPanel1.add(upd);
        upd.setBounds(260, 120, 100, 23);

        del.setText("Delete");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        jPanel1.add(del);
        del.setBounds(160, 120, 63, 23);

        nrd.setText("(There are no rows to be displayed)");
        jPanel1.add(nrd);
        nrd.setBounds(230, 680, 180, 14);

        udd.setText("update in detail");
        udd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uddActionPerformed(evt);
            }
        });
        jPanel1.add(udd);
        udd.setBounds(400, 120, 110, 23);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("<---");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(1200, 20, 53, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drug/624dd0a951a1e8a118215b1b24a0da59-pharmacy-logo-by-vexels.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(810, 160, 540, 500);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 80, 1420, 20);

        jLabel3.setForeground(new java.awt.Color(0, 102, 153));
        jLabel3.setText("Search by Manager:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 260, 110, 14);
        jPanel1.add(tt2);
        tt2.setBounds(160, 250, 200, 30);

        g2.setText("GO");
        g2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g2ActionPerformed(evt);
            }
        });
        jPanel1.add(g2);
        g2.setBounds(400, 250, 47, 23);

        jLabel4.setForeground(new java.awt.Color(0, 102, 153));
        jLabel4.setText("Search by Name:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 200, 90, 14);
        jPanel1.add(tt1);
        tt1.setBounds(160, 190, 200, 30);

        g1.setText("GO");
        g1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g1ActionPerformed(evt);
            }
        });
        jPanel1.add(g1);
        g1.setBounds(400, 190, 47, 23);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1420, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
storeinfo obj=new storeinfo();
this.dispose();
obj.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void updActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updActionPerformed

          mod=(DefaultTableModel)jTable1.getModel();
        String val=String.valueOf((mod.getValueAt(jTable1.getSelectedRow(),0)));
        String val1=String.valueOf((mod.getValueAt(jTable1.getSelectedRow(),1)));
        String val2=String.valueOf((mod.getValueAt(jTable1.getSelectedRow(),2)));
        String val3=String.valueOf((mod.getValueAt(jTable1.getSelectedRow(),3)));
        String val4=String.valueOf((mod.getValueAt(jTable1.getSelectedRow(),4)));
        int v=Integer.parseInt(val);
        
      
        String h="iopop";
        try{
         DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
        Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","abhij","naanu");  
        Statement stmt=con.createStatement();
    
        stmt.executeUpdate("update stores set name='"+val1+"',address='"+val2+"',contact='"+val3+"',store_man='"+val4+"' where store_id='"+v+"'");
        mod.getDataVector().removeAllElements();
        revalidate();
        ResultSet rs=stmt.executeQuery("select * from stores");
         while(rs.next()==true)
    {
         mod.insertRow(mod.getRowCount(),new Object[]{Integer.toString(rs.getInt(1)),(rs.getString(2)),(rs.getString(3)),(rs.getString(4)),(rs.getString(5))});
    }
        

        
    con.close();
    }
    catch(Exception e)
    {
        
        JOptionPane.showMessageDialog(jPanel1, e, "Error", JOptionPane.ERROR_MESSAGE);
    }
    
        


        // TODO add your handling code here:
    }//GEN-LAST:event_updActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed

        mod=(DefaultTableModel)jTable1.getModel();
        String val;
        val=String.valueOf((mod.getValueAt(jTable1.getSelectedRow(),0)));
        int at=Integer.parseInt(val);
        System.out.println(at);
        try{
         DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
        Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","abhij","naanu");  
        Statement stmt=con.createStatement();
    PreparedStatement pstmt = con.prepareStatement("delete from stores where store_id=?");
    pstmt.setInt(1, at);
    pstmt.executeUpdate();
    mod.removeRow(jTable1.getSelectedRow());  
    con.close();
    }
    catch(Exception e)
    {
        
        JOptionPane.showMessageDialog(jPanel1, e, "Error", JOptionPane.ERROR_MESSAGE);
    }
        

        // TODO add your handling code here:
    }//GEN-LAST:event_delActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        upd.setEnabled(true);
        udd.setEnabled(true);
        del.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusLost
upd.setHideActionText(rootPaneCheckingEnabled);        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1FocusLost

    private void jTable1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTable1InputMethodTextChanged

    }//GEN-LAST:event_jTable1InputMethodTextChanged

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void uddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uddActionPerformed

     mod=(DefaultTableModel)jTable1.getModel();
        String val=String.valueOf((mod.getValueAt(jTable1.getSelectedRow(),0)));
        String val1=String.valueOf((mod.getValueAt(jTable1.getSelectedRow(),1)));
        String val2=String.valueOf((mod.getValueAt(jTable1.getSelectedRow(),2)));
        String val3=String.valueOf((mod.getValueAt(jTable1.getSelectedRow(),3)));
        String val4=String.valueOf((mod.getValueAt(jTable1.getSelectedRow(),4)));
        int v=Integer.parseInt(val);
        storeinfo obj=new storeinfo(v,val1,val2,val3,val4);
        this.dispose();
        obj.setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_uddActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        this.dispose();
        admin obj=new admin();
        obj.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void g1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g1ActionPerformed
        try {
            String a=tt1.getText();
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","abhij","naanu");
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery("select * from stores where name like '%"+a+"%'");
            mod=(DefaultTableModel)jTable1.getModel();
            mod.getDataVector().removeAllElements();
            revalidate();
            while(rs.next())
            {
                 mod.insertRow(mod.getRowCount(),new Object[]{Integer.toString(rs.getInt(1)),(rs.getString(2)),(rs.getString(3)),(rs.getString(4)),(rs.getString(5))});
 
            }
            tt1.setText("");
            
            
        } catch (SQLException ex) {
            Logger.getLogger(stores.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_g1ActionPerformed

    private void g2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g2ActionPerformed

        try {
            String a=tt2.getText();
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","abhij","naanu");
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery("select * from stores where store_man like '%"+a+"%'");
            mod=(DefaultTableModel)jTable1.getModel();
            mod.getDataVector().removeAllElements();
            revalidate();
            while(rs.next())
            {
                 mod.insertRow(mod.getRowCount(),new Object[]{Integer.toString(rs.getInt(1)),(rs.getString(2)),(rs.getString(3)),(rs.getString(4)),(rs.getString(5))});
 
            }
            tt2.setText("");
            
            
        } catch (SQLException ex) {
            Logger.getLogger(stores.class.getName()).log(Level.SEVERE, null, ex);
        }
        

        // TODO add your handling code here:
    }//GEN-LAST:event_g2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton del;
    private javax.swing.JButton g1;
    private javax.swing.JButton g2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nrd;
    private javax.swing.JTextField tt1;
    private javax.swing.JTextField tt2;
    private javax.swing.JButton udd;
    private javax.swing.JButton upd;
    // End of variables declaration//GEN-END:variables
}
