/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package drug;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASHWINI A M
 */
public class storeinfo extends javax.swing.JFrame {

    /**
     * Creates new form storeinfo
     */
    public int a;
    public String val1,val2,val3,val4;
    public static int isd=200;
    DefaultTableModel mod;
    
    public storeinfo(int a, String val1, String val2, String val3, String val4)
    {
        try {
            initComponents();
            jButton1.setVisible(false);
            jButton2.setVisible(false);
            this.a=a;
            this.val1=val1;
            this.val2=val2;
            this.val3=val3;
            this.val4=val4;
            
            storeid.setText(Integer.toString(a));
            t1.setText((val1));
            t2.setText((val2));
            t3.setText((val3));
            t4.setText(val4);
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","abhij","naanu");
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery("select pass from stores where store_id="+a+"");
            while(rs.next())
            {
            pas.setText(rs.getString(1));
            }
            
            mod=(DefaultTableModel)jTable1.getModel();
            mod.getDataVector().removeAllElements();
                revalidate();
            rs=stmt.executeQuery("select * from stores");
            while(rs.next())
            {
                  mod.insertRow(mod.getRowCount(),new Object[]{Integer.toString(rs.getInt(1)),(rs.getString(2)),(rs.getString(3)),(rs.getString(4)),(rs.getString(5))});
            }
            
            up1.setVisible(true);
            
        } catch (SQLException ex) {
            Logger.getLogger(storeinfo.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
    }
    public storeinfo() {
        
       
        
        initComponents();
        up1.setVisible(false);
        cl1.setVisible(false);
        try{
        
        DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
        Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","abhij","naanu");  
        Statement stmt=con.createStatement();
        mod=(DefaultTableModel)jTable1.getModel();
            mod.getDataVector().removeAllElements();
                revalidate();
       ResultSet rs=stmt.executeQuery("select * from stores order by store_id");
       
        while(rs.next()==true)
        {   isd=rs.getInt(1);
      
          mod.insertRow(mod.getRowCount(),new Object[]{Integer.toString(rs.getInt(1)),(rs.getString(2)),(rs.getString(3)),(rs.getString(4)),(rs.getString(5))});
        
        }
        isd++;
        spas.setText("Assign a password for store "+Integer.toString(isd));
        storeid.setText(Integer.toString(isd));
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        storeid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t2 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        spas = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pas = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        up1 = new javax.swing.JButton();
        cl1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("<---");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Store Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Store_id:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 83, 58, -1));

        storeid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeidActionPerformed(evt);
            }
        });
        jPanel2.add(storeid, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 77, 97, 28));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Name:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 123, 58, -1));

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        jPanel2.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 123, 186, 28));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Address:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 169, 58, -1));

        t2.setColumns(20);
        t2.setRows(5);
        jScrollPane1.setViewportView(t2);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 169, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Contact:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 277, 58, -1));

        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        jPanel2.add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 271, 186, 28));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Manager:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 323, 58, -1));

        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });
        jPanel2.add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 317, 186, 28));

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Password Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 204))); // NOI18N

        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Password:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pas, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spas, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 290, 150));

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, -1));

        up1.setText("Update");
        up1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up1ActionPerformed(evt);
            }
        });
        jPanel2.add(up1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));

        cl1.setText("Clear");
        cl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cl1ActionPerformed(evt);
            }
        });
        jPanel2.add(cl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 660, 400));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Store_id", "Name", "address", "contact", "Manager"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 50, 440, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1580, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void storeidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_storeidActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
t1.setText("");
t2.setText("");
t3.setText("");
t4.setText("");
pas.setText("");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        
        
        String name;
        String addr;
        String contact;
        String man;
        
        try {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","abhij","naanu");
          
            Statement stmt=con.createStatement();

             mod=(DefaultTableModel)jTable1.getModel();
            mod.getDataVector().removeAllElements();
                revalidate();
            name=t1.getText();
            addr=t2.getText();
            contact=t3.getText();
            man=t4.getText();
            String h=pas.getText();
            stmt.executeUpdate("insert into stores values("+isd+",'"+name+"','"+addr+"','"+contact+"','"+man+"','"+h+"')");
             int tem=0;
            int zero=0;
            int uuu=201;
            int str[]=new int[100];          
            ResultSet rs=stmt.executeQuery("select med_id from medicine");
            while(rs.next())
            {
                str[tem]=rs.getInt(1);
                tem++;
            }
            for(int i=0;i<tem;i++)
            {
                stmt.executeUpdate("insert into quant values("+str[i]+","+isd+","+zero+")");
                
            }
            
            
           
            
            storeid.setText(Integer.toString(isd+1));
            isd++;
            spas.setText("Assign a password for store "+Integer.toString(isd));
            t1.setText("");
            t2.setText("");
            t3.setText("");
            t4.setText("");
            pas.setText("");
            rs=stmt.executeQuery("select * from stores order by store_id");
            while(rs.next()==true)
        {   
      
          mod.insertRow(mod.getRowCount(),new Object[]{Integer.toString(rs.getInt(1)),(rs.getString(2)),(rs.getString(3)),(rs.getString(4)),(rs.getString(5))});
        
        }
           
            
            
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(storeinfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
stores qwv=new stores();
this.dispose();
qwv.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void up1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up1ActionPerformed

        try{
         DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
        Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","abhij","naanu");  
        Statement stmt=con.createStatement();
        val1=t1.getText();
        val2=t2.getText();
        val3=t3.getText();
        val4=t4.getText();
        String h=pas.getText();
        System.out.println(a+" "+val1+" "+val2+" "+val3+" "+val4);
        stmt.executeUpdate("update stores set name='"+val1+"',address='"+val2+"',contact='"+val3+"',store_man='"+val4+"',pass='"+h+"' where store_id='"+a+"'");
        
        mod=(DefaultTableModel)jTable1.getModel();
            mod.getDataVector().removeAllElements();
            revalidate();
            
            ResultSet rs=stmt.executeQuery("select * from stores order by store_id");
            while(rs.next()==true)
        {   
      
          mod.insertRow(mod.getRowCount(),new Object[]{Integer.toString(rs.getInt(1)),(rs.getString(2)),(rs.getString(3)),(rs.getString(4)),(rs.getString(5))});
        
        }
        
        con.close();
       }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(jPanel1, e, "Error", JOptionPane.ERROR_MESSAGE);
       }
        

        // TODO add your handling code here:
    }//GEN-LAST:event_up1ActionPerformed

    private void cl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cl1ActionPerformed

        t1.setText("");
t2.setText("");
t3.setText("");
t4.setText("");
pas.setText("");
        


        // TODO add your handling code here:
    }//GEN-LAST:event_cl1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(storeinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(storeinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(storeinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(storeinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new storeinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cl1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPasswordField pas;
    private javax.swing.JLabel spas;
    private javax.swing.JTextField storeid;
    private javax.swing.JTextField t1;
    private javax.swing.JTextArea t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JButton up1;
    // End of variables declaration//GEN-END:variables
}
